#pragma once
#define ERR_DB_NOERR				0x00
#define ERR_DB_INITCONNFAIL			0x01
#define ERR_DB_CREATECONNFAIL		0x02
#define ERR_DB_SETCHASETFAIL		0x03
#define ERR_DB_STARTTRANFAIL		0x04
#define ERR_DB_CANCELTRANFAIL		0x05
#define ERR_DB_COMMITTRANFAIL		0x06
#define ERR_DB_EXECUTESQL			0x07
#define ERR_DB_QUERYEMPTY			0x08
#define ERR_DB_ALLOCCONNFAIL		0x09
